//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class file1 extends JPanel {
    private JLabel jcomp1;

    public file1() {
        //construct components
        jcomp1 = new JLabel ("hello bro");

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 581));
        setLayout (null);

        //add components
        add (jcomp1);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (345, 230, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new file1());
        frame.pack();
        frame.setVisible (true);
    }
}
